# IMU和GNSS数据文件路径
# imudata and gnssdata filepath
imupath: "/Users/0-0mashuo/Desktop/Clion/CombinedNavigation/Dataset/imu.ASC"
gnsspath: "/Users/0-0mashuo/Desktop/Clion/CombinedNavigation/Dataset/开阔rtkRes.pos"

# 观测模型:
# 1 :  GNSS位置观测
# 2 :  GNSS位置、速度观测
# 3 :  GNSS位置、速度及里程计观测
obsmodel: 2

# 输出文件夹路径
# output folder path
outputpath: "/Users/0-0mashuo/Desktop/Clion/CombinedNavigation/Dataset/"

# IMU文件格式
# 22 - novatel ascii 文本
# 33 - imr文件
# 44 - 按行排列的ascii文件  second theta-x theta-y theta-z dv-x dv-y dv-z 默认轴系ned
imufileformat: 22
# IMU原始数据频率
# IMU datarate [Hz]
imudatarate: 100

# GNSS 结果文件格式
# 1 - gpst-week gpst-second d-lat d-lon d-h lat-std lon-std h-std v-n v-e v-u vn-std ve-std vd-std
gnssfileformat: 1
gnssfilecol: 14

# 是否自己对准
# 1 - 是
# 0 - 否
ifalign: 1
# 对准起始时间
# 0 - IMU文件开头
alignbegintime: 0

# 处理时间段，结束时间设置为-1时则处理至IMU文件结束
starttime: 360555.25
endtime: 361495.99

# 初始状态
# 初始位置, 纬度 经度 高程
initpos: [ 30.5281113284  ,114.3557629661  ,22.440 ]

# 初始速度, 北向速度, 东向速度, 垂向速度
initvel: [ -0.062 , 1.026 , 0.010 ]

# 初始姿态, 欧拉角(ZYX旋转顺序), 横滚, 俯仰, 航向
initatt: [  -0.7838703327,-0.1439787743 ,93.8217170742 ]

# 初始IMU零偏和比例因子, IMU的三个轴(前、右、下)
initgyrbias: [ 6.944e-4,6.944e-4,6.944e-4 ]    # [deg/h]
initaccbias: [ 98, 98, 98]    # [mGal]
initgyrscale: [ 0, 0, 0 ]   # [ppm]
initaccscale: [ 0, 0, 0 ]   # [ppm]

# 初始状态标准差
# 初始位置标准差, 导航坐标系下 北向, 东向和垂向
initposstd: [ 0.003 ,0.003 ,0.006 ]

# 初始速度标准差, 导航坐标系下北向、东向和垂向速度
initvelstd: [ 0.001 ,0.001 ,0.001   ]

# 初始姿态标准差, 横滚、俯仰、航向角标准差
initattstd: [ 0.00, 0.00, 0.00 ]

# 初始IMU零偏和比例因子标准差, IMU的三个轴(这里设置为初始状态的0.1倍)
# 如果不指定，默认按照IMU零偏和比例因子误差参数设定
initbgstd: [ 6.944e-6,6.944e-6,6.944e-6 ]       # [deg/h]
initbastd: [ 9.8, 9.8, 9.8 ]                    # [mGal]
initsgstd: [ 0, 0, 0 ]                          # [ppm]
initsastd: [ 0, 0, 0 ]                          # [ppm]

# IMU噪声建模参数, IMU的三个轴
imunoise:
  arw: [9.17e-5, 9.17e-5, 9.17e-5]           # [deg/sqrt(hr)]
  vrw: [1.67e-4, 1.67e-4, 1.67e-4]          # [m/s/sqrt(hr)]
  gbstd: [0.05, 0.05, 0.05]                    # [deg/hr]
  abstd: [2.5, 2.5, 2.5]                       # [mGal]
  gsstd: [1000, 1000, 1000]                          # [ppm]
  asstd: [1000, 1000, 1000]                          # [ppm]
  corrtime: [1.0, 1.0, 1.0, 1.0]            # [Tgb,Tab,Tgs,Tas] [h]

# 天线杆臂, IMU坐标系前右下方向
antlever: [ 0.1090,-0.0325,-0.9160]
