# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/0-0mashuo/Desktop/Clion/CombinedNavigation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/0-0mashuo/Desktop/Clion/CombinedNavigation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/0-0mashuo/Desktop/Clion/CombinedNavigation/CMakeFiles /Users/0-0mashuo/Desktop/Clion/CombinedNavigation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/0-0mashuo/Desktop/Clion/CombinedNavigation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CombinedNavigation

# Build rule for target.
CombinedNavigation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CombinedNavigation
.PHONY : CombinedNavigation

# fast build rule for target.
CombinedNavigation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/build
.PHONY : CombinedNavigation/fast

#=============================================================================
# Target rules for targets named CombinedNavigation_autogen

# Build rule for target.
CombinedNavigation_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CombinedNavigation_autogen
.PHONY : CombinedNavigation_autogen

# fast build rule for target.
CombinedNavigation_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation_autogen.dir/build.make CMakeFiles/CombinedNavigation_autogen.dir/build
.PHONY : CombinedNavigation_autogen/fast

CombinedNavigation_autogen/mocs_compilation.o: CombinedNavigation_autogen/mocs_compilation.cpp.o
.PHONY : CombinedNavigation_autogen/mocs_compilation.o

# target to build an object file
CombinedNavigation_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/CombinedNavigation_autogen/mocs_compilation.cpp.o
.PHONY : CombinedNavigation_autogen/mocs_compilation.cpp.o

CombinedNavigation_autogen/mocs_compilation.i: CombinedNavigation_autogen/mocs_compilation.cpp.i
.PHONY : CombinedNavigation_autogen/mocs_compilation.i

# target to preprocess a source file
CombinedNavigation_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/CombinedNavigation_autogen/mocs_compilation.cpp.i
.PHONY : CombinedNavigation_autogen/mocs_compilation.cpp.i

CombinedNavigation_autogen/mocs_compilation.s: CombinedNavigation_autogen/mocs_compilation.cpp.s
.PHONY : CombinedNavigation_autogen/mocs_compilation.s

# target to generate assembly for a file
CombinedNavigation_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/CombinedNavigation_autogen/mocs_compilation.cpp.s
.PHONY : CombinedNavigation_autogen/mocs_compilation.cpp.s

Sources/BasicFuns.o: Sources/BasicFuns.cpp.o
.PHONY : Sources/BasicFuns.o

# target to build an object file
Sources/BasicFuns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/BasicFuns.cpp.o
.PHONY : Sources/BasicFuns.cpp.o

Sources/BasicFuns.i: Sources/BasicFuns.cpp.i
.PHONY : Sources/BasicFuns.i

# target to preprocess a source file
Sources/BasicFuns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/BasicFuns.cpp.i
.PHONY : Sources/BasicFuns.cpp.i

Sources/BasicFuns.s: Sources/BasicFuns.cpp.s
.PHONY : Sources/BasicFuns.s

# target to generate assembly for a file
Sources/BasicFuns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/BasicFuns.cpp.s
.PHONY : Sources/BasicFuns.cpp.s

Sources/main.o: Sources/main.cpp.o
.PHONY : Sources/main.o

# target to build an object file
Sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/main.cpp.o
.PHONY : Sources/main.cpp.o

Sources/main.i: Sources/main.cpp.i
.PHONY : Sources/main.i

# target to preprocess a source file
Sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/main.cpp.i
.PHONY : Sources/main.cpp.i

Sources/main.s: Sources/main.cpp.s
.PHONY : Sources/main.s

# target to generate assembly for a file
Sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/main.cpp.s
.PHONY : Sources/main.cpp.s

Sources/mainwindow.o: Sources/mainwindow.cpp.o
.PHONY : Sources/mainwindow.o

# target to build an object file
Sources/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/mainwindow.cpp.o
.PHONY : Sources/mainwindow.cpp.o

Sources/mainwindow.i: Sources/mainwindow.cpp.i
.PHONY : Sources/mainwindow.i

# target to preprocess a source file
Sources/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/mainwindow.cpp.i
.PHONY : Sources/mainwindow.cpp.i

Sources/mainwindow.s: Sources/mainwindow.cpp.s
.PHONY : Sources/mainwindow.s

# target to generate assembly for a file
Sources/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/Sources/mainwindow.cpp.s
.PHONY : Sources/mainwindow.cpp.s

lib/Filter/cKalman.o: lib/Filter/cKalman.cpp.o
.PHONY : lib/Filter/cKalman.o

# target to build an object file
lib/Filter/cKalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/lib/Filter/cKalman.cpp.o
.PHONY : lib/Filter/cKalman.cpp.o

lib/Filter/cKalman.i: lib/Filter/cKalman.cpp.i
.PHONY : lib/Filter/cKalman.i

# target to preprocess a source file
lib/Filter/cKalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/lib/Filter/cKalman.cpp.i
.PHONY : lib/Filter/cKalman.cpp.i

lib/Filter/cKalman.s: lib/Filter/cKalman.cpp.s
.PHONY : lib/Filter/cKalman.s

# target to generate assembly for a file
lib/Filter/cKalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/lib/Filter/cKalman.cpp.s
.PHONY : lib/Filter/cKalman.cpp.s

src/FileIO/cFileConvertor.o: src/FileIO/cFileConvertor.cpp.o
.PHONY : src/FileIO/cFileConvertor.o

# target to build an object file
src/FileIO/cFileConvertor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cFileConvertor.cpp.o
.PHONY : src/FileIO/cFileConvertor.cpp.o

src/FileIO/cFileConvertor.i: src/FileIO/cFileConvertor.cpp.i
.PHONY : src/FileIO/cFileConvertor.i

# target to preprocess a source file
src/FileIO/cFileConvertor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cFileConvertor.cpp.i
.PHONY : src/FileIO/cFileConvertor.cpp.i

src/FileIO/cFileConvertor.s: src/FileIO/cFileConvertor.cpp.s
.PHONY : src/FileIO/cFileConvertor.s

# target to generate assembly for a file
src/FileIO/cFileConvertor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cFileConvertor.cpp.s
.PHONY : src/FileIO/cFileConvertor.cpp.s

src/FileIO/cfileBase.o: src/FileIO/cfileBase.cpp.o
.PHONY : src/FileIO/cfileBase.o

# target to build an object file
src/FileIO/cfileBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileBase.cpp.o
.PHONY : src/FileIO/cfileBase.cpp.o

src/FileIO/cfileBase.i: src/FileIO/cfileBase.cpp.i
.PHONY : src/FileIO/cfileBase.i

# target to preprocess a source file
src/FileIO/cfileBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileBase.cpp.i
.PHONY : src/FileIO/cfileBase.cpp.i

src/FileIO/cfileBase.s: src/FileIO/cfileBase.cpp.s
.PHONY : src/FileIO/cfileBase.s

# target to generate assembly for a file
src/FileIO/cfileBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileBase.cpp.s
.PHONY : src/FileIO/cfileBase.cpp.s

src/FileIO/cfileReader.o: src/FileIO/cfileReader.cpp.o
.PHONY : src/FileIO/cfileReader.o

# target to build an object file
src/FileIO/cfileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileReader.cpp.o
.PHONY : src/FileIO/cfileReader.cpp.o

src/FileIO/cfileReader.i: src/FileIO/cfileReader.cpp.i
.PHONY : src/FileIO/cfileReader.i

# target to preprocess a source file
src/FileIO/cfileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileReader.cpp.i
.PHONY : src/FileIO/cfileReader.cpp.i

src/FileIO/cfileReader.s: src/FileIO/cfileReader.cpp.s
.PHONY : src/FileIO/cfileReader.s

# target to generate assembly for a file
src/FileIO/cfileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileReader.cpp.s
.PHONY : src/FileIO/cfileReader.cpp.s

src/FileIO/cfileSaver.o: src/FileIO/cfileSaver.cpp.o
.PHONY : src/FileIO/cfileSaver.o

# target to build an object file
src/FileIO/cfileSaver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileSaver.cpp.o
.PHONY : src/FileIO/cfileSaver.cpp.o

src/FileIO/cfileSaver.i: src/FileIO/cfileSaver.cpp.i
.PHONY : src/FileIO/cfileSaver.i

# target to preprocess a source file
src/FileIO/cfileSaver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileSaver.cpp.i
.PHONY : src/FileIO/cfileSaver.cpp.i

src/FileIO/cfileSaver.s: src/FileIO/cfileSaver.cpp.s
.PHONY : src/FileIO/cfileSaver.s

# target to generate assembly for a file
src/FileIO/cfileSaver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/FileIO/cfileSaver.cpp.s
.PHONY : src/FileIO/cfileSaver.cpp.s

src/GNSS/GNSSType.o: src/GNSS/GNSSType.cpp.o
.PHONY : src/GNSS/GNSSType.o

# target to build an object file
src/GNSS/GNSSType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/GNSS/GNSSType.cpp.o
.PHONY : src/GNSS/GNSSType.cpp.o

src/GNSS/GNSSType.i: src/GNSS/GNSSType.cpp.i
.PHONY : src/GNSS/GNSSType.i

# target to preprocess a source file
src/GNSS/GNSSType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/GNSS/GNSSType.cpp.i
.PHONY : src/GNSS/GNSSType.cpp.i

src/GNSS/GNSSType.s: src/GNSS/GNSSType.cpp.s
.PHONY : src/GNSS/GNSSType.s

# target to generate assembly for a file
src/GNSS/GNSSType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/GNSS/GNSSType.cpp.s
.PHONY : src/GNSS/GNSSType.cpp.s

src/INS/INSData.o: src/INS/INSData.cpp.o
.PHONY : src/INS/INSData.o

# target to build an object file
src/INS/INSData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/INS/INSData.cpp.o
.PHONY : src/INS/INSData.cpp.o

src/INS/INSData.i: src/INS/INSData.cpp.i
.PHONY : src/INS/INSData.i

# target to preprocess a source file
src/INS/INSData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/INS/INSData.cpp.i
.PHONY : src/INS/INSData.cpp.i

src/INS/INSData.s: src/INS/INSData.cpp.s
.PHONY : src/INS/INSData.s

# target to generate assembly for a file
src/INS/INSData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/INS/INSData.cpp.s
.PHONY : src/INS/INSData.cpp.s

src/LC/LooseCombination.o: src/LC/LooseCombination.cpp.o
.PHONY : src/LC/LooseCombination.o

# target to build an object file
src/LC/LooseCombination.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/LC/LooseCombination.cpp.o
.PHONY : src/LC/LooseCombination.cpp.o

src/LC/LooseCombination.i: src/LC/LooseCombination.cpp.i
.PHONY : src/LC/LooseCombination.i

# target to preprocess a source file
src/LC/LooseCombination.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/LC/LooseCombination.cpp.i
.PHONY : src/LC/LooseCombination.cpp.i

src/LC/LooseCombination.s: src/LC/LooseCombination.cpp.s
.PHONY : src/LC/LooseCombination.s

# target to generate assembly for a file
src/LC/LooseCombination.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CombinedNavigation.dir/build.make CMakeFiles/CombinedNavigation.dir/src/LC/LooseCombination.cpp.s
.PHONY : src/LC/LooseCombination.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CombinedNavigation_autogen"
	@echo "... CombinedNavigation"
	@echo "... CombinedNavigation_autogen/mocs_compilation.o"
	@echo "... CombinedNavigation_autogen/mocs_compilation.i"
	@echo "... CombinedNavigation_autogen/mocs_compilation.s"
	@echo "... Sources/BasicFuns.o"
	@echo "... Sources/BasicFuns.i"
	@echo "... Sources/BasicFuns.s"
	@echo "... Sources/main.o"
	@echo "... Sources/main.i"
	@echo "... Sources/main.s"
	@echo "... Sources/mainwindow.o"
	@echo "... Sources/mainwindow.i"
	@echo "... Sources/mainwindow.s"
	@echo "... lib/Filter/cKalman.o"
	@echo "... lib/Filter/cKalman.i"
	@echo "... lib/Filter/cKalman.s"
	@echo "... src/FileIO/cFileConvertor.o"
	@echo "... src/FileIO/cFileConvertor.i"
	@echo "... src/FileIO/cFileConvertor.s"
	@echo "... src/FileIO/cfileBase.o"
	@echo "... src/FileIO/cfileBase.i"
	@echo "... src/FileIO/cfileBase.s"
	@echo "... src/FileIO/cfileReader.o"
	@echo "... src/FileIO/cfileReader.i"
	@echo "... src/FileIO/cfileReader.s"
	@echo "... src/FileIO/cfileSaver.o"
	@echo "... src/FileIO/cfileSaver.i"
	@echo "... src/FileIO/cfileSaver.s"
	@echo "... src/GNSS/GNSSType.o"
	@echo "... src/GNSS/GNSSType.i"
	@echo "... src/GNSS/GNSSType.s"
	@echo "... src/INS/INSData.o"
	@echo "... src/INS/INSData.i"
	@echo "... src/INS/INSData.s"
	@echo "... src/LC/LooseCombination.o"
	@echo "... src/LC/LooseCombination.i"
	@echo "... src/LC/LooseCombination.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

